# Generated by Django 3.2 on 2024-03-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_auto_20171222_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='プロジェクト名')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='終了日')),
                ('description', models.TextField(blank=True, verbose_name='プロジェクトの詳細')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='club',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='dte',
            field=models.CharField(default='XXXX', max_length=10, verbose_name='DTE'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='XXXX.YYYY', max_length=10, primary_key=True, serialize=False, verbose_name='EID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eno',
            field=models.CharField(default='000000000', max_length=8, verbose_name='社員番号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=50, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='ミドル'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.CharField(default='AIR', max_length=20, verbose_name='オフィス'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='<django.db.models.fields.CharField>@accenture.com', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='XXXX', max_length=20, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='YYYY', max_length=20, verbose_name='姓'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
