# Generated by Django 3.2 on 2024-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='EID'),
        ),
    ]
