# Generated by Django 3.2 on 2024-03-02 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Resister Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>.<django.db.models.fields.CharField>', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='EID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.CharField(default='000000000', max_length=8, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='XXXX', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='YYYY', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(default='AIR', max_length=20, verbose_name='Office'),
        ),
    ]
