# Generated by Django 3.2 on 2024-03-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20240302_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>.<django.db.models.fields.CharField>', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='EID'),
        ),
    ]
