# Generated by Django 3.2 on 2024-03-02 07:19

from django.db import migrations

def remove_duplicates(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    for eid in Employee.objects.values_list('eid', flat=True).distinct():
        employees = list(Employee.objects.filter(eid=eid))
        if len(employees) > 1:
            for employee in employees[1:]:
                employee.eid = None  # or generate a new unique eid
                employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_eid'),  # replace with your previous migration
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
