# Generated by Django 3.2 on 2024-03-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20240302_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.CharField(default='000000000', max_length=8, unique=True, verbose_name='Employee No.'),
        ),
    ]
