# Generated by Django 3.2 on 2024-03-02 07:27

from django.db import migrations, models
import uuid

def remove_duplicates(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    for eid in Employee.objects.values_list('eid', flat=True).distinct():
        employees = list(Employee.objects.filter(eid=eid))
        if len(employees) > 1:
            for employee in employees[1:]:
                employee.eid = None  # or generate a new unique eid
                employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_eno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=uuid.uuid1, max_length=50, primary_key=True, serialize=False, verbose_name='EID'),
        ),
         migrations.RunPython(remove_duplicates),
    ]
