# Generated by Django 3.2 on 2024-03-02 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=uuid.uuid1, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='EID'),
        ),
    ]
