# Generated by Django 3.2 on 2024-03-02 07:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employee_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Resister Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Resister Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=uuid.uuid1, max_length=50, primary_key=True, serialize=False, verbose_name='EID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Project Detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
