# Generated by Django 3.2 on 2024-03-02 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20240302_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='EID'),
        ),
    ]
