# Generated by Django 3.2 on 2024-03-03 01:13

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20240302_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='aquire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(default=employee.models.get_or_create_eid, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='skill',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='need_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(default=employee.models.get_or_create_eid, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='XXXX', max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='XXXX', max_length=100, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='training',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(default='XXXX', max_length=100),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
