# Generated by Django 3.2 on 2024-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20240303_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='aquire_date',
            new_name='acquire_date',
        ),
    ]
